Add validations and model specs
NatiDeme/blog-site-with-ruby pull request #3
Opened 2022-09-16 09:39 UTC by NatiDeme

# Changes in this PR:
- No linter errors
- Included Validations:
   **For the User model:**
    - Name must not be blank.
   - PostsCounter must be an integer greater than or equal to zero.

    **For the Post model:**

   -  Title must not be blank.
   -  Title must not exceed 250 characters.
   -  CommentsCounter must be an integer greater than or equal to zero.
   -  LikesCounter must be an integer greater than or equal to zero.
  
- Imlemented unit specs for all of your models' methods and validations.

2022-09-16 11:18 UTC, dasileker requested changes
### **Hi @NatiDeme,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- Linters are green ✅.
- PR is very nice 👌.

## Required Changes ♻️
_Check the comments under the review._

- Hello and good job on the validation and spec but you have added the spec files incorrectly. the spec files should be added using the RSpec method, [check this tutorial about rspec](https://www.tutorialspoint.com/rspec/rspec_introduction.htm)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 11:18 UTC, dasileker commented on app/models/specs/models/like_spec.rb
> +  end
- [ ] Hello and excellent work, but the spec files should be created using the Rpsec.

2022-09-16 11:18 UTC, dasileker commented on app/models/specs/models/post_spec.rb
> +      expect(subject).to be_valid
- [ ] The same thing is also should e done for this file.

2022-09-16 11:18 UTC, dasileker commented on app/models/specs/models/user_spec.rb
> +      expect(subject).to_not be_valid
- [ ] also this file

2022-09-16 12:06 UTC, GzimAsani requested changes
### Hello @NatiDeme              :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your project  :+1:  
 
 ## Required Changes 

- [ ] Please implement the changes on your readme file asked by the previous reviewer and don't forget to include in your readme file the steps on how to test your project
- [ ] Check the comments below :arrow_double_down: 






 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 12:06 UTC, GzimAsani commented on spec/models/post_spec.rb
> +    user1 = User.create(name: 'Lolade', bio: 'Public Administator', posts_counter: 0)
- [ ] Unfortunately, now I am getting this error when trying to run your tests :confused: 
![image](https://user-images.githubusercontent.com/62705947/190634865-09d13e4f-a026-427d-b06a-002244b64326.png)

2022-09-17 09:04 UTC, Rustamxon7 approved these changes
## Hello @NatiDeme 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-17 09:08 UTC, merged